[databases]
  [databases.development]
    type = "mysql"
    user = "hiveuser"
    password = "#"
    port = "3306"
    host = "localhost"
    database = "tests"
    max_open_connection = "10"
    max_idle_connection = "10"
  [databases.production]
    type = "postgres"
    user = "benny"
    password = "#"
    port = "5432"
    host = "localhost"
    database = "postgres"
    max_open_connection = "10"
    max_idle_connection = "10"
